---
- name: "Verify the initial certificate date validity"
  shell: "openssl x509 -noout -enddate -in /etc/pki/vdsm/certs/{{vdsmcert}}"
  register: result
- debug: var=result.stdout

- block:
    - name: "Installing pip3"
      package:
        name: 
          - python3-pip
          - gcc
          - openssl-devel
          - libcurl-devel
          - libxml2-devel
          - python36-devel

    - name: "Update pip"
      pip:
        name: pip
        state: latest

    - name: "Installing ovirtsdk4"
      pip: 
        name: ovirt-engine-sdk-python

    - name: Get hosts from all engines
      ovirt_host_info:
        auth:
          url: "https://{{item}}.v100.abes.fr/ovirt-engine/api"
          username: admin@internal
          password: "{{ ovirt_password if item != 'infra' else ovirt_password_infra }}"
          #ca_file: /tmp/ca.pem
          insecure: true
        pattern: "name={{inventory_hostname}}*"
      loop: "{{engines}}"
      loop_control:
        label: "{{item}}"
      register: result
    - set_fact:
          server: "{{result.results|selectattr('ovirt_hosts')|map(attribute='item')|join(',')}}"
  run_once: yes
  when: server is not defined
  delegate_to: localhost
